name: React CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: self-hosted  # Sử dụng runner tự quản

    continue-on-error: true  # Bỏ qua lỗi và tiếp tục pipeline

    steps:
      # Lấy mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Thay đổi phiên bản Node.js nếu cần

      # Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Kiểm tra lint
      - name: Lint code
        run: npm run lint -- --quiet || echo "Linting failed, but continuing the pipeline"  # Bỏ qua lỗi lint

      # Chạy test
      - name: Run tests
        run: npm test -- --watchAll=false --maxWorkers=2 || echo "Tests failed, but continuing the pipeline"  # Bỏ qua lỗi test

      # Build dự án
      - name: Build project
        run: npm run build || echo "Build failed, but continuing the pipeline"  # Bỏ qua lỗi build
        
  deploy:
    needs: build  # Chạy deploy sau khi build thành công
    runs-on: self-hosted  # Hoặc sử dụng môi trường phù hợp với bạn

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (again for deploy job)
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Đảm bảo Node.js được cài đặt trong job deploy

      - name: Install Vercel CLI via npm
        run: |
          npm install -g vercel  # Cài đặt Vercel CLI bằng npm

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Lấy token từ GitHub Secrets
        run: |
          vercel --prod --token $VERCEL_TOKEN

